spring:
  jpa:
    hibernate:
      ddl-auto: none

calendar:
  github:
    organizations:
      - micrometer-metrics
      - r2dbc
      - reactor
      - spring-cloud
      - spring-gradle-plugins
      - spring-io
      - spring-projects
  release:
    project_aliases:
      'Toolsuite Distribution': STS
